language: ruby
cache: bundler
rvm:
  - 2.1.4
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rspec spec
before_script:
  - mysql -e 'create database exhibit_admin_test'
